name: Linux (clang)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Setup required packages"
        run: sudo apt-get install -y binutils-dev libssl-dev uuid-dev

      - name: "Setup clang"
        uses: egor-tensin/setup-clang@v1

      - name: "Build"
        run: |
          cmake -Bbuild
          cmake --build build
