name: MacOS

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install deps"
        run: |
          brew update
          brew install glfw

      - name: "Build"
        run: |
          cmake -Bbuild
          cmake --build build
