name: Windows (Visual Studio)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Setup Visual Studio"
        uses: egor-tensin/vs-shell@v2

      - name: "Build"
        run: |
          cmake -Bbuild
          cmake --build build
