name: Windows (Visual Studio)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgCommitId: 8eb57355a4ffb410a2e94c07b4dca2dffbee8e50

      - name: Run CMake with vcpkg.json manifest
        uses: lukka/run-cmake@v10
